[package]
name = "chalcedony"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.7"

# for more detailed flamegraphs
[profile.release]
debug = true
opt-level = 3

